"""AI Agent Marketplace — system catalog definitions."""

from __future__ import annotations

MARKETPLACE_AGENTS: list[dict] = [
    {
        "slug": "research",
        "name": "Research Agent",
        "description": "Deep research from verified sources, fact-checking, citations, and structured briefs for documentaries.",
        "icon": "🔍",
        "category": "intelligence",
        "studio_route": "research",
        "available_permissions": ["ai.generate", "research.edit", "research.approve", "asset.read"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "temperature": 0.3,
            "max_sources": 12,
            "citation_style": "apa",
        },
        "config_schema": {
            "provider": {"type": "string", "enum": ["openai", "anthropic", "google"]},
            "model": {"type": "string"},
            "temperature": {"type": "number", "min": 0, "max": 1},
            "max_sources": {"type": "integer", "min": 1, "max": 50},
            "citation_style": {"type": "string", "enum": ["apa", "mla", "chicago"]},
        },
    },
    {
        "slug": "finance",
        "name": "Finance Agent",
        "description": "Revenue modeling, budget forecasts, sponsorship ROI, and production cost analysis.",
        "icon": "💰",
        "category": "business",
        "studio_route": "revenue",
        "available_permissions": ["ai.generate", "analytics.read", "admin.read"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "currency": "USD",
            "forecast_months": 12,
            "include_sponsorship": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "currency": {"type": "string"},
            "forecast_months": {"type": "integer", "min": 1, "max": 36},
            "include_sponsorship": {"type": "boolean"},
        },
    },
    {
        "slug": "sports",
        "name": "Sports Agent",
        "description": "Live match context, athlete profiles, rivalry narratives, and sports documentary angles.",
        "icon": "⚽",
        "category": "intelligence",
        "studio_route": "research",
        "available_permissions": ["ai.generate", "research.edit", "asset.read"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "sports_focus": ["football", "cricket", "basketball"],
            "include_live_data": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "sports_focus": {"type": "array"},
            "include_live_data": {"type": "boolean"},
        },
    },
    {
        "slug": "news",
        "name": "News Agent",
        "description": "Breaking news monitoring, source aggregation, and timely documentary hooks from global feeds.",
        "icon": "📰",
        "category": "intelligence",
        "studio_route": "research",
        "available_permissions": ["ai.generate", "research.edit", "publish.schedule"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "fetch_interval_minutes": 15,
            "regions": ["global", "india", "us"],
            "auto_summarize": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "fetch_interval_minutes": {"type": "integer"},
            "regions": {"type": "array"},
            "auto_summarize": {"type": "boolean"},
        },
    },
    {
        "slug": "seo",
        "name": "SEO Agent",
        "description": "Titles, metadata, schema markup, keyword clusters, and platform-specific SEO variants.",
        "icon": "📊",
        "category": "distribution",
        "studio_route": "seo",
        "available_permissions": ["ai.generate", "publish.schedule", "analytics.read"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "variant_count": 5,
            "platforms": ["youtube", "originals", "blog"],
            "include_schema": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "variant_count": {"type": "integer", "min": 1, "max": 20},
            "platforms": {"type": "array"},
            "include_schema": {"type": "boolean"},
        },
    },
    {
        "slug": "podcast",
        "name": "Podcast Agent",
        "description": "Episode outlines, show notes, interview questions, and audio-first script adaptations.",
        "icon": "🎧",
        "category": "production",
        "studio_route": "scripts",
        "available_permissions": ["ai.generate", "script.edit", "voice.generate"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "episode_length_minutes": 45,
            "format": "documentary",
            "include_show_notes": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "episode_length_minutes": {"type": "integer"},
            "format": {"type": "string"},
            "include_show_notes": {"type": "boolean"},
        },
    },
    {
        "slug": "thumbnail",
        "name": "Thumbnail Agent",
        "description": "CTR-optimized thumbnail concepts, A/B variants, and platform-specific crop recommendations.",
        "icon": "🖼️",
        "category": "creative",
        "studio_route": "images",
        "available_permissions": ["ai.generate", "asset.manage", "asset.upload"],
        "default_config": {
            "provider": "openai",
            "model": "dall-e-3",
            "variant_count": 4,
            "aspect_ratios": ["16:9", "1:1"],
            "style": "cinematic",
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "variant_count": {"type": "integer"},
            "aspect_ratios": {"type": "array"},
            "style": {"type": "string"},
        },
    },
    {
        "slug": "translation",
        "name": "Translation Agent",
        "description": "Multi-language scripts, subtitles, dubbing prep, and localization memory for global distribution.",
        "icon": "🌐",
        "category": "distribution",
        "studio_route": "translation",
        "available_permissions": ["ai.generate", "script.edit", "publish.schedule"],
        "default_config": {
            "provider": "openai",
            "model": "gpt-4o",
            "target_languages": ["es", "hi", "ar", "fr"],
            "preserve_tone": True,
            "glossary_enabled": True,
        },
        "config_schema": {
            "provider": {"type": "string"},
            "model": {"type": "string"},
            "target_languages": {"type": "array"},
            "preserve_tone": {"type": "boolean"},
            "glossary_enabled": {"type": "boolean"},
        },
    },
    {
        "slug": "voice",
        "name": "Voice Agent",
        "description": "Narration synthesis, voice cloning prep, subtitle timing, and multi-speaker dialogue.",
        "icon": "🎙️",
        "category": "production",
        "studio_route": "voice",
        "available_permissions": ["ai.generate", "asset.upload", "timeline.edit"],
        "default_config": {
            "provider": "elevenlabs",
            "voice_id": "default",
            "stability": 0.75,
            "speed": 1.0,
            "subtitle_format": "srt",
        },
        "config_schema": {
            "provider": {"type": "string"},
            "voice_id": {"type": "string"},
            "stability": {"type": "number"},
            "speed": {"type": "number"},
            "subtitle_format": {"type": "string"},
        },
    },
    {
        "slug": "publishing",
        "name": "Publishing Agent",
        "description": "Multi-platform publishing, scheduling, approval workflows, and webhook dispatch.",
        "icon": "🚀",
        "category": "distribution",
        "studio_route": "publishing-agent",
        "available_permissions": ["publish.schedule", "publish.approve", "ai.generate", "analytics.read"],
        "default_config": {
            "platforms": ["originals", "youtube", "instagram"],
            "require_approval": True,
            "auto_schedule": False,
            "webhook_enabled": True,
        },
        "config_schema": {
            "platforms": {"type": "array"},
            "require_approval": {"type": "boolean"},
            "auto_schedule": {"type": "boolean"},
            "webhook_enabled": {"type": "boolean"},
        },
    },
]

DEFAULT_GRANTED_PERMISSIONS: dict[str, list[str]] = {
    "research": ["ai.generate", "research.edit", "asset.read"],
    "finance": ["ai.generate", "analytics.read"],
    "sports": ["ai.generate", "research.edit"],
    "news": ["ai.generate", "research.edit"],
    "seo": ["ai.generate", "publish.schedule"],
    "podcast": ["ai.generate", "script.edit"],
    "thumbnail": ["ai.generate", "asset.manage"],
    "translation": ["ai.generate", "script.edit"],
    "voice": ["ai.generate", "asset.upload"],
    "publishing": ["publish.schedule", "publish.approve", "ai.generate"],
}
