apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: untold-ingress
  namespace: untold
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  tls:
    - hosts:
        - studio.untold.com
        - api.untold.com
      secretName: untold-tls
  rules:
    - host: studio.untold.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: untold-web
                port:
                  number: 80
    - host: api.untold.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: untold-api
                port:
                  number: 8000
