apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: untold
resources:
  - namespace.yaml
  - configmap.yaml
  - backup-scripts-configmap.yaml
  - backup-pvc.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - backup-cronjob.yaml
  - servicemonitor.yaml
